In [1]:
import numpy as np

In [ ]:
l = [10,20,30,40,50]

arr = np.array(l)

print(f'Shape- {arr.shape}') 
print(f'Dimension- {arr.ndim}') 
print(f'Data Types - {arr.dtype}')
print(f'Size - {arr.size}')

array([10, 20, 30, 40, 50])

In [7]:
arr = np.array([5, 10, 15, 20, 25, 30, 35])

"""
    Print:

First element
Last element
Elements from 15 to 30
Every second element

"""

print(arr[0])
print(arr[-1])
print(arr[2:6])
print(arr[::2])

5
35
[15 20 25 30]
[ 5 15 25 35]


In [10]:
# Exercise 3: Boolean Filtering
arr = np.array([12, 45, 23, 67, 89, 10, 5])

'''
Print:

Numbers greater than 30
Numbers less than 20
'''

print(arr[arr>30])
print(arr[arr<20])

[45 67 89]
[12 10  5]


In [16]:
# Exercise 4: Reshape


arr = np.array([1, 2, 3, 4, 5, 6])
arr.shape
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [21]:
# Exercise 5: Statistics

arr = np.array([10, 20, 30, 40, 50])
 
''' 
Find:

Sum
Mean
Maximum
Minimum

'''

print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())

150
30.0
50
10


In [22]:
# Exercise 6: Broadcasting
arr = np.array([1, 2, 3, 4, 5])

# Add 10 to every element.

print(arr+10)


[11 12 13 14 15]


In [ ]:
# Exercise 7: Mini Challenge
marks = np.array([45, 67, 89, 34, 90, 56, 78])

'''
Print:

All marks above 60
Average mark
Highest mark
Lowest mark
Number of students who scored above 60
'''
print(f'All marks above 60 - {marks[marks>60]}')
print(f'Average mark - {marks.mean()}')
print(f'Highest mark - {marks.max()}')
print(f'Lowest mark - {marks.min()}')
print(f'Number of students who scored above 60 - {marks[marks>60].size}')

All marks above 60 - [67 89 90 78]
Average mark - 65.57142857142857
Average mark - 90
Lowest mark - 34
Number of students who scored above 60 - 4
