In [1]:
import numpy as np

### Basic Array Creation

In [2]:
arr = np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
l = [[1,2,3],[4,5,6],[7,8,9]]

np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr = np.arange(0,12,2)

arr

array([ 0,  2,  4,  6,  8, 10])

In [20]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
np.zeros((4,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
arr = np.linspace(1,12,12)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [31]:
arr = np.linspace(0,12,5)
arr

array([ 0.,  3.,  6.,  9., 12.])

In [36]:
arr = np.random.rand(10)
arr

array([0.30138196, 0.01509406, 0.78539377, 0.65521593, 0.40733486,
       0.82595721, 0.73048503, 0.08492929, 0.58161358, 0.87866557])

In [37]:
np.random.randn(10)

array([-0.97219591, -0.28055165, -0.09328173, -1.00236822, -1.18104711,
       -1.69600582, -1.25875283, -1.37227969, -0.45508222,  0.2829573 ])

In [58]:
arr = np.random.randint(10,20,10) # generate 10 random number between 10 and 20
arr

array([10, 11, 19, 11, 17, 13, 11, 12, 14, 16], dtype=int32)

## Array Attributes

In [63]:
l = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(l)

arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
arr.shape

(3, 3)

In [64]:
arr.size

9

In [65]:
arr.dtype

dtype('int64')

In [66]:
arr.ndim

2

In [67]:
arr.itemsize

8

In [69]:
arr.min()

np.int64(1)

In [70]:
arr.max()

np.int64(9)

In [71]:
arr.sum()

np.int64(45)

In [72]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [73]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [74]:
np.min(arr, axis=1)

array([1, 4, 7])

In [75]:
arr.mean()

np.float64(5.0)

In [78]:
arr.std()

np.float64(2.581988897471611)

In [77]:
arr.size

9

# Reshaping and Resizing


In [80]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [85]:
arr = arr.reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])