In [1]:
import numpy as np

### Basic Array Creation

In [2]:
arr = np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
l = [[1,2,3],[4,5,6],[7,8,9]]

np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr = np.arange(0,12,2)

arr

array([ 0,  2,  4,  6,  8, 10])

In [20]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
np.zeros((4,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
arr = np.linspace(1,12,12)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [31]:
arr = np.linspace(0,12,5)
arr

array([ 0.,  3.,  6.,  9., 12.])

In [36]:
arr = np.random.rand(10)
arr

array([0.30138196, 0.01509406, 0.78539377, 0.65521593, 0.40733486,
       0.82595721, 0.73048503, 0.08492929, 0.58161358, 0.87866557])

In [37]:
np.random.randn(10)

array([-0.97219591, -0.28055165, -0.09328173, -1.00236822, -1.18104711,
       -1.69600582, -1.25875283, -1.37227969, -0.45508222,  0.2829573 ])