In [1]:
import numpy as np

# Numpy indexing and slicing of vector

In [2]:
arr = np.arange(11,22)

In [3]:
arr[6]

np.int64(17)

In [4]:
arr[1:5]

array([12, 13, 14, 15])

In [7]:
arr = np.arange(1,31).reshape((6,5))
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [14]:
arr[0][4]

np.int64(5)

In [18]:
arr[5,4]

np.int64(30)

In [25]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [29]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [31]:
arr[2:5,2:5]

array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [34]:
arr[3:7,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [35]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

## Boolean Indexing

In [48]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [52]:
arr = np.arange(11,21)
bool_index = arr %2==0
bool_index
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

array([12, 14, 16, 18, 20])