In [1]:
import numpy as np

## arithmetic operation

In [8]:
a1 = np.arange(1,6)
a2 = np.arange(6,11)


In [9]:
a1

array([1, 2, 3, 4, 5])

In [10]:
a2

array([ 6,  7,  8,  9, 10])

In [11]:
a1+a2

array([ 7,  9, 11, 13, 15])