In [3]:
import numpy as np

In [4]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],  # Student 1
    [19, 92, 88],  # Student 2
    [17, 76, 95],  # Student 3
    [18, 65, 70],  # Student 4
    [20, 90, 85]   # Student 5
])

## Valid Sudoku


In [5]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [6]:
b = np.sum(s,axis=1)
b

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [7]:
b==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [8]:
for i in b:
    if i == 45:
        print('Valid for rows') 
        
    else:
        print('Invalid for rows')
        

Valid for rows
Valid for rows
Valid for rows
Valid for rows
Valid for rows
Valid for rows
Valid for rows
Valid for rows
Valid for rows


In [9]:
b = np.sum(s,axis=0)
count = 0
for i in b:
    
    if i == 45:
        print(f'Columns:{count} Valid for columns') 
        count+=1
        
        
    else:
        print(f'Columns:{count} Invalid for columns')
        count+=1
        

Columns:0 Valid for columns
Columns:1 Valid for columns
Columns:2 Valid for columns
Columns:3 Valid for columns
Columns:4 Valid for columns
Columns:5 Valid for columns
Columns:6 Valid for columns
Columns:7 Valid for columns
Columns:8 Valid for columns


In [10]:
t = s[:3,:3].sum()
t


np.int64(45)

In [11]:
t = s[:3,3:6].sum()
t

np.int64(45)

In [12]:
t = s[:3,6:9].sum()
t

np.int64(45)

In [13]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [15]:
for i in range(0,9,3):
    for j in range(0,9,3):
        print(s[i:i+3])
    


[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]]
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]]
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]]
[[8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]]
[[8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]]
[[8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]]
[[9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
[[9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
[[9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
