In [269]:
import numpy as np

In [270]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],  # Student 1
    [19, 92, 88],  # Student 2
    [17, 76, 95],  # Student 3
    [18, 65, 70],  # Student 4
    [20, 90, 85]   # Student 5
])

## Valid Sudoku


In [271]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [272]:
b = np.sum(s,axis=1)
b

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [273]:
b==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [274]:
for i in b:
    if i == 45:
        print('Valid for rows') 
        
    else:
        print('Invalid for rows')
        

Valid for rows
Valid for rows
Valid for rows
Valid for rows
Valid for rows
Valid for rows
Valid for rows
Valid for rows
Valid for rows


In [275]:
b = np.sum(s,axis=0)
count = 0
for i in b:
    
    if i == 45:
        print(f'Columns:{count} Valid for columns') 
        count+=1
        
        
    else:
        print(f'Columns:{count} Invalid for columns')
        count+=1
        

Columns:0 Valid for columns
Columns:1 Valid for columns
Columns:2 Valid for columns
Columns:3 Valid for columns
Columns:4 Valid for columns
Columns:5 Valid for columns
Columns:6 Valid for columns
Columns:7 Valid for columns
Columns:8 Valid for columns


In [276]:
t = s[:3,:3].sum()
t


np.int64(45)

In [277]:
t = s[:3,3:6].sum()
t

np.int64(45)

In [278]:
t = s[:3,6:9].sum()
t

np.int64(45)

In [279]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [280]:
for i in range(0,9,3):
    for j in range(0,9,3):
        print(s[i:i+3])
    


[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]]
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]]
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]]
[[8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]]
[[8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]]
[[8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]]
[[9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
[[9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
[[9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


## General Questions 

In [281]:

# Columns: [Age, Math Marks, Science Marks]
df = np.array([
    [18, 85, 78],  # Student 1
    [19, 92, 88],  # Student 2
    [17, 76, 95],  # Student 3
    [18, 65, 70],  # Student 4
    [20, 90, 85]   # Student 5
])

In [282]:
df.shape

(5, 3)

## Find the average age of students

In [283]:
average_age = np.mean(df[:,0])

print(f'Average age: {average_age}')

Average age: 18.4


# Extract math marks of all students

In [284]:
df

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [285]:
math_marks = df[:, 1]

print('All math marks: ',math_marks)

All math marks:  [85 92 76 65 90]


## Find the highest science mark.

In [286]:
highest_science_mark = np.max(df[:, 2])

print('Highest Science Mark: ', highest_science_mark)

Highest Science Mark:  95


# Get the fetails of the student who scored more than 90 in math

In [287]:
above_90 = df[df[:, 1] > 90]

above_90

array([[19, 92, 88]])

In [288]:
rows = np.where(df[:, 1] > 90)
print(rows)
df[rows]

(array([1]),)


array([[19, 92, 88]])

## Increase the marks of all student by  5

In [289]:
df

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [290]:
df[:,1] = df[:,1]+5

df


array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

## Find how many students are younger than 19

In [291]:
row = df[df[:, 0] < 19]

print('Total: ', row.shape[0])
print('Total: ', row.shape[0])


Total:  3
Total:  3


## Find the average marks in each subject (column-wise mean).


In [292]:
df

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [293]:
np.mean(df[:, 1:], axis=0)

array([86.6, 83.2])

## Get data of students who scored at least 80 in both subjects

In [294]:
df

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [295]:
df[(df[:, 1]>=80) & (df[:,2])]

array([[18, 90, 78],
       [18, 90, 78],
       [19, 97, 88],
       [18, 90, 78],
       [19, 97, 88]])

## Replace all science mark less then 75 with 0

In [296]:
df

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [300]:
df[:,2][df[:,2] <75] = 0

df

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])